import type { Permission, PermissionGrant, SystemRoleKey } from '@synapse/types';

const grants = (...permissions: Permission[]): PermissionGrant[] =>
  permissions.map((permission) => ({ permission }));

/** Conjunto fixo de permissoes de cada role padrao (§3). Nao e customizavel pelo
 *  tenant — para isso existe o cargo PERSONALIZADO, que tem permissoes proprias
 *  guardadas em Firestore/memoria (ver RoleRepository). */
export const DEFAULT_ROLE_PERMISSIONS: Record<SystemRoleKey, PermissionGrant[]> = {
  SUPER_ADMIN_SAAS: grants(
    'produto.visualizar',
    'produto.criar',
    'produto.editar',
    'produto.excluir',
    'produto.importar',
    'estoque.visualizar',
    'estoque.ajustar',
    'estoque.transferir',
    'estoque.inventariar',
    'venda.criar',
    'venda.editar',
    'venda.cancelar',
    'venda.aprovarDesconto',
    'fiscal.emitir',
    'fiscal.cancelar',
    'fiscal.visualizar',
    'fiscal.configurar',
    'financeiro.visualizar',
    'financeiro.editar',
    'financeiro.conciliar',
    'filial.gerenciar',
    'filial.configurar',
    'cargo.gerenciar',
    'usuario.gerenciar',
    'preco.gerenciar',
    'preco.negociarExtra',
    'cliente.gerenciar',
    'fornecedor.gerenciar',
    'auditoria.visualizar',
  ),
  ADMIN_EMPRESA: grants(
    'produto.visualizar',
    'produto.criar',
    'produto.editar',
    'produto.excluir',
    'produto.importar',
    'estoque.visualizar',
    'estoque.ajustar',
    'estoque.transferir',
    'estoque.inventariar',
    'venda.criar',
    'venda.editar',
    'venda.cancelar',
    'venda.aprovarDesconto',
    'fiscal.emitir',
    'fiscal.cancelar',
    'fiscal.visualizar',
    'fiscal.configurar',
    'financeiro.visualizar',
    'financeiro.editar',
    'financeiro.conciliar',
    'filial.gerenciar',
    'filial.configurar',
    'cargo.gerenciar',
    'usuario.gerenciar',
    'preco.gerenciar',
    'preco.negociarExtra',
    'cliente.gerenciar',
    'fornecedor.gerenciar',
    'auditoria.visualizar',
  ),
  ADMIN_FILIAL: grants(
    'produto.visualizar',
    'produto.editar',
    'estoque.visualizar',
    'estoque.ajustar',
    'estoque.transferir',
    'estoque.inventariar',
    'venda.criar',
    'venda.editar',
    'venda.cancelar',
    'venda.aprovarDesconto',
    'fiscal.emitir',
    'fiscal.visualizar',
    'financeiro.visualizar',
    'filial.configurar',
    'preco.negociarExtra',
    'cliente.gerenciar',
    'fornecedor.gerenciar',
  ),
  GERENTE: grants(
    'produto.visualizar',
    'produto.editar',
    'estoque.visualizar',
    'estoque.ajustar',
    'estoque.transferir',
    'venda.criar',
    'venda.editar',
    'venda.cancelar',
    'venda.aprovarDesconto',
    'fiscal.visualizar',
    'financeiro.visualizar',
    'preco.negociarExtra',
    'cliente.gerenciar',
  ),
  VENDEDOR: grants(
    'produto.visualizar',
    'estoque.visualizar',
    'venda.criar',
    'venda.editar',
    'fiscal.visualizar',
    'cliente.gerenciar',
  ),
  CAIXA: grants(
    'produto.visualizar',
    'estoque.visualizar',
    'venda.criar',
    'fiscal.emitir',
    'fiscal.visualizar',
  ),
  ESTOQUE: grants(
    'produto.visualizar',
    'estoque.visualizar',
    'estoque.ajustar',
    'estoque.transferir',
    'estoque.inventariar',
    'fornecedor.gerenciar',
  ),
  FINANCEIRO: grants(
    'produto.visualizar',
    'financeiro.visualizar',
    'financeiro.editar',
    'financeiro.conciliar',
    'fiscal.visualizar',
    'cliente.gerenciar',
  ),
};
