import { item, montarMenu, SEPARADOR as SEP, submenu } from '../menu.utils';

/** Cadastros, na ordem do Syndata. Conteudo dos submenus conferido nos prints,
 *  menos os marcados com [inferido], que ainda esperam captura de tela. */
export const CADASTROS = montarMenu('Cadastros', [
  // [inferido]
  submenu('Parâmetros da Empresa', [
    item('Dados da Empresa'),
    item('Configuração por Filial', { para: '/configuracoes/filiais' }),
    item('Parâmetros Gerais'),
  ]),
  submenu('Financeiro', [
    item('Plano de Contas'),
    item('Centro de Custos'),
    SEP,
    item('Contas'),
    SEP,
    item('Portadores'),
    // [inferido]
    submenu('Bancos', [item('Bancos'), item('Agências')]),
    SEP,
    item('Tipos de Documentos'),
    item('Convênios'),
    SEP,
    item('Condições de Pagamento'),
    item('Grupo de Condições de Pagamento'),
    SEP,
    item('Tipo de Lançamento em Títulos a Receber'),
    item('Tipo de Lançamento em Títulos a Pagar'),
  ]),
  submenu('Fiscais', [
    item('Séries de Notas Fiscais'),
    SEP,
    item('Contabilista'),
    item('Intermediador da Transação (Marketplace)'),
  ]),
  SEP,
  item('Transportadoras'),
  item('Praças e Regiões'),
  item('Assessores de Venda'),
  item('Mesas / Cartões'),
  SEP,
  submenu('Clientes', [
    item('Clientes'),
    SEP,
    item('Grupo de Clientes'),
    item('Sub-Grupo de Clientes'),
    item('Grupo Econômico'),
    item('Prospecção'),
    item('Segmento Empresarial'),
    item('Lote de Cobrança'),
    SEP,
    item('Configuração de Clientes em Lote'),
  ]),
  submenu('Fornecedores', [
    item('Fornecedores'),
    SEP,
    item('Grupo de Fornecedores'),
    item('Sub-Grupo de Fornecedores'),
  ]),
  submenu('Funcionários', [
    item('Funcionários'),
    SEP,
    item('Cargos', { para: '/configuracoes/cargos' }),
    item('Departamentos'),
  ]),
  submenu('Produtos / Serviços', [
    item('Produtos / Serviços', { para: '/cadastros/produtos' }),
    item('Cotação da Moeda Estrangeira'),
    SEP,
    item('Unidades de Medidas'),
    item('Grupos de Produtos'),
    item('Sub-Grupo de Produtos'),
    item('Linha de Produtos'),
    item('Marcas'),
    item('Similares'),
    item('Localização do Produto'),
    item('Grupo de Promoção'),
    SEP,
    item('Cores'),
    item('Tamanhos'),
    SEP,
    item('Departamentos do Produto'),
    item('Configuração de Produtos para Autoatendimento'),
    SEP,
    item('Ajuste de Preço dos Produtos'),
    item('Aplicar Tabela de ICMS/ICMS ST'),
    item('Atualização de Tabelas da SEFAZ'),
    item('Produtos Favoritos'),
    SEP,
    item('Configuração de Produtos em Lote'),
    item('Importar Códigos de Benefícios Fiscais'),
  ]),
  SEP,
  submenu('Relatórios', [
    item('Clientes'),
    item('Fornecedores'),
    item('Funcionários'),
    item('Assessores de Venda'),
    SEP,
    item('Etiqueta de Produtos'),
    item('Etiqueta de Clientes'),
    item('Etiqueta de Produto Pesado em Balança'),
  ]),
]);
